### ISSUE TITLE
fatal_error { inspect: [Function: inspect] }

### ISSUE THREAD

**Issue by goldingdamien** [salimkayabasi/types-checker#17]
I am getting the following error. What is the problem?

```
$ tscheck --install
Starting types-checker@0.0.9
These modules are missing @types/fs-extra @types/node
Running yarn add --dev @types/fs-extra @types/node
fatal_error { inspect: [Function: inspect] }
```

**Comment by salimkayabasi** [comment]
default package manager is `yarn` and this is an expected error if you haven't installed `yarn` yet.

as a quick solution, you can use `tscheck --install -N` command to switch for `npm` instead of `yarn`
